# 1. Conexao com o Banco (Le as variaveis do Heroku/STS4)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# 2. Driver e Dialeto
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 3. Inicializacao do Banco (Executa o seu schema.sql)
# 'always' executa o schema.sql toda vez que a app inicia
spring.sql.init.mode=never
# 'none' ou 'validate' evita que o Hibernate tente criar tabelas ao mesmo tempo que o script SQL
spring.jpa.hibernate.ddl-auto=validate

# 4. Configuracoes extras para PostgreSQL/Supabase
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Configuracoes para o Banco de Dados H2
# datasource
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.url=jdbc:h2:mem:testedb
#spring.datasource.username=sa
#spring.datasource.password=sa

# jpa
#spring.jpa.defer-datasource-initialization=true
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=none

# h2
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
